name: wcnf_demo
seed: 1

log_level: info
report_interval: 1
eval_interval: 50
save_interval: 50

data_path: /pub/ssd/yef
train_sets:
  - name: train_sample
    samples: 2
    max_tries: 10
    max_flips: 500
    iterations: 1000

eval_set:
  name: eval_sample
  samples: 2
  max_tries: 10
  max_flips: 500

model_path: False

gnn_hidden_size: 32
readout_hidden_size: 64

cycles: 1
optimizer: RMSprop
lr: 0.0005
lr_milestones: [200, 500, 1000, 5000]
lr_decay: 0.5

method: reinforce
discount: 0.25
walk_prob: 0.5
